### ISSUE TITLE
slackin: invite to signup flow “Continue with Google” fails on OAuth2 handoff

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/infra#137]
**What were you trying to do?**
I was helping a new employee invite themselves to slack at slack.moov.io and the "Continue with Google" page failed on a google.com callback page. A generic error was returned about it being unable to complete the request.

**What did you expect to see?**
"Continue with Google" should pass and allow a new user to signup from their email invite. 

**How can we reproduce the problem?**
I invited a `*@moov.io` address, so maybe that's it? We allow any domain though, so it should't be a configuration problem.

**Comment by adamdecaf** [comment]
FYI she was able to signup by adding a password, but the OIDC / OAuth2 flow should work.

**Comment by adamdecaf** [comment]
The slackin config / deployment is here. Maybe we just need to restart it? 

https://github.com/moov-io/infra/blob/master/lib/sales/30-slackin-extended.yml

**Comment by darwinz** [comment]
I was unable to reproduce this bug.  The Google Oauth flow actually starts at `moov-io.slack.com`, so it seems this may have been an issue on Slack's side
