### ISSUE TITLE
slackin: total "users registered so far" is behind 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/infra#141]
On [slack.moov.io](https://slack.moov.io/) we have a "**836** users are registered so far." block that comes from [slackin-extended](https://github.com/emedvedev/slackin-extended) by default. However, this is behind/cached for some reason. We've had questions why the counts are different, so this confusing aspect needs fixed. 

Our configuration / deployment is located here: https://github.com/moov-io/infra/blob/master/lib/sales/30-slackin-extended.yml#L41

**Comment by adamdecaf** [comment]
@GrahamMcBain is filing an upstream

**Comment by darwinz** [comment]
The issue was a bug in the OSS project `slackin-extended` that we use.  I have patched the bug with this PR:  https://github.com/emedvedev/slackin-extended/pull/254

Working on deploying to prod right now
