### ISSUE TITLE
go/lint: enforce camelCase in json struct tags

### ISSUE THREAD

**Issue by sethlivingston** [moov-io/infra#275]
camelCase is the capitalization preferred in JavaScript. I know JSON is read by many different languages, but having a mix of different capitalization in json struct tags isn't a good idea. We should ask authors to use camelCase.

**Comment by adamdecaf** [comment]
Go doesn't have warnings, but we can probably require camelCase. Go doesn't care when reading JSON, but some languages like javascript do.

**Comment by adamdecaf** [comment]
Looks like we can support this request with https://golangci-lint.run/usage/linters/#tagliatelle

**Comment by adamdecaf** [comment]
Yes, I think we can just enable the linter. By default it won't require us to have field names and struct tags match, which is probably fine. I know there are some cases where we deviate struct from json for readability. The defaults for json and yaml camelcase work for us. If we wanted to be stricter we could force `use-field-name: true` and offer an env var to disable.
