### ISSUE TITLE
spike: support for local development (Minikube, tilt) 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/infra#34]
**What were you trying to do?**
Wanted to run the infrastructure environment locally in Minikube. 

**What did you expect to see?**
Documentation and scripts to show me how to get the environment up and running. 

**What did you see?**
The assumption that you need to run the system in Google Container Cloud

**How can we reproduce the problem?**

Read the docs.

**Comment by adamdecaf** [comment]
I'm 👍 for this and we should keep an `envs/dev` (and `dev.moov.io`) environment in our repository. (Similar for a [`sbx.moov.io`](https://github.com/moov-io/infra/issues/11) as a staging environment.)

Docker for [Windows/Mac ships with a Kubernetes cluster](https://blog.docker.com/2018/07/kubernetes-is-now-available-in-docker-desktop-stable-channel/) that's much easier to use than minikube (historically minikube has been a complicated mess of enable/disable flags). There's no support for Linux though.

**Comment by adamdecaf** [comment]
My plan is pretty much this: 

https://medium.com/localz-engineering/kubernetes-traefik-locally-with-a-wildcard-certificate-e15219e5255d

**Comment by adamdecaf** [comment]
Tilt is another (new) option: https://github.com/windmilleng/tilt - I haven't tried it out

**Comment by adamdecaf** [comment]
I tried out [tilt](https://github.com/windmilleng/tilt#tilt) recently and it seems pretty nice. Having progress bars and easy log access for each local container is super handy. We should be able to reuse our Kubernetes manifests also. 

cc @wadearnold thoughts? tilt just requires docker and kubectl.

**Comment by adamdecaf** [comment]
I've written up a quick section on using Tilt. I'm going to try using that from now on in my work. It seems to be a great tool so far.

https://github.com/moov-io/infra#local-development

cc @wadearnold

**Comment by adamdecaf** [comment]
The Tilt setup is working, but we need to upgrade it. There's a quick guide for doing so https://docs.tilt.dev/resource_assembly_migration.html 

Also, paygate has a docker-compose setup for quick local running of our stack.
