### ISSUE TITLE
apps: fuzz api routes 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/infra#75]
There's a project called [KissPeter/APIFuzzer](https://github.com/KissPeter/APIFuzzer) that looks to read an OpenAPI spec file and fuzz the endpoints looking for crashers or weird outputs. Let's try it out and see if anything comes up.

**Comment by adamdecaf** [comment]
Currently blocked trying to read YAML (it assumes JSON) -- https://github.com/KissPeter/APIFuzzer/issues/30

**Comment by KissPeter** [comment]
https://github.com/KissPeter/APIFuzzer/issues/30 is ready. Feel free to use it. Any feedback is welcome

**Comment by adamdecaf** [comment]
Thanks! We'll report any issues.
